### ISSUE TITLE
Call to undefined method Vitalybaev\LaravelDkim\DkimMailServiceProvider::setMailerDependencies()

### ISSUE THREAD

**Issue by donmbelembe** [vitalybaev/laravel5-dkim#2]
i'm getting this error. please help

laravel 5.4

Call to undefined method Vitalybaev\LaravelDkim\DkimMailServiceProvider::setMailerDependencies()
in DkimMailServiceProvider.php (line 26)

**Comment by vitalybaev** [comment]
@donmbelembe thanks for reporting this. I'll make some modifications to fix this ASAP.

**Comment by vitalybaev** [comment]
@donmbelembe I've published `v0.1.4` release. Please update and test.
